/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.Crud.Search.SearchProducts;
import java.awt.Color;
import javax.swing.ImageIcon;


/**
 *
 * @author ideapad330S
 */
public class SalesUI extends javax.swing.JFrame {

    public boolean existsPanel = false;
    private SalesUI emp ;
    public SalesUI() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
         ImageIcon icon = new ImageIcon("C:\\Users\\ideapad330S\\Documents\\NetBeansProjects"
                 + "\\Pharmacy Software\\src\\UI\\Images\\Icono.png");
         this.setIconImage(icon.getImage());
         this.emp = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        productsBtn = new javax.swing.JButton();
        patientsBtn = new javax.swing.JButton();
        salesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(238, 231, 231));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        productsBtn.setBackground(new java.awt.Color(255, 255, 255));
        productsBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        productsBtn.setForeground(new java.awt.Color(255, 255, 255));
        productsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-pills-32.png"))); // NOI18N
        productsBtn.setText("Products");
        productsBtn.setContentAreaFilled(false);
        productsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        productsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsBtnMouseExited(evt);
            }
        });

        patientsBtn.setBackground(new java.awt.Color(255, 255, 255));
        patientsBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        patientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        patientsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-patients-32.png"))); // NOI18N
        patientsBtn.setText("Patients");
        patientsBtn.setContentAreaFilled(false);
        patientsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        patientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientsBtnMouseExited(evt);
            }
        });

        salesBtn.setBackground(new java.awt.Color(51, 153, 255));
        salesBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        salesBtn.setForeground(new java.awt.Color(255, 255, 255));
        salesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-online-store-32.png"))); // NOI18N
        salesBtn.setText("Sales");
        salesBtn.setContentAreaFilled(false);
        salesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salesBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        salesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(productsBtn)
                .addGap(15, 15, 15)
                .addComponent(patientsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(patientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(salesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(productsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/v1033-a-11-b-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(110, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 319, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsBtnMouseClicked

        if (!existsPanel) {
             SearchProducts productsFrame = new SearchProducts(jLabel1,emp );
            jPanel2.add(productsFrame);
            productsFrame.setVisible(true);
            existsPanel = true;
            if (productsFrame.isShowing()) {
                jLabel1.setVisible(false);
            } 
        } 
    }//GEN-LAST:event_productsBtnMouseClicked

    private void productsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsBtnMouseEntered
      productsBtn.setForeground(Color.lightGray);
       
    }//GEN-LAST:event_productsBtnMouseEntered

    private void productsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsBtnMouseExited
      productsBtn.setForeground(Color.white);
    }//GEN-LAST:event_productsBtnMouseExited

    private void patientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_patientsBtnMouseClicked

    private void patientsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsBtnMouseEntered
   patientsBtn.setForeground(Color.lightGray);
    }//GEN-LAST:event_patientsBtnMouseEntered

    private void patientsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsBtnMouseExited
       patientsBtn.setForeground(Color.white);
    }//GEN-LAST:event_patientsBtnMouseExited

    private void salesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salesBtnMouseClicked

    private void salesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtnMouseEntered
        salesBtn.setForeground(Color.lightGray);
    }//GEN-LAST:event_salesBtnMouseEntered

    private void salesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtnMouseExited
      salesBtn.setForeground(Color.white);
    }//GEN-LAST:event_salesBtnMouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton patientsBtn;
    private javax.swing.JButton productsBtn;
    private javax.swing.JButton salesBtn;
    // End of variables declaration//GEN-END:variables

}
